### ISSUE TITLE
Fix: Handle CUDA device-side error

### ISSUE THREAD

**Issue by nickcom007** [FLock-io/llm-loss-validator#25]
`CUDA error: device-side assert triggered` happens from time to time in the `loop` function. Once it's triggered, all following validation will keep failing due to this. We need a bash script to monitor and restart the `loop` process based on the error.

- `validate` function should exit the process whenever it captures this exception with a special exit code
- The bash script should capture the exit code and decide whether to restart the `loop` process
- If it's caused by this error, we should not mark the assignment as `failed`, because it's not actually caused by OOM
- The bash script should have a `usage()` defined
- The bash script should take in necessary ENVs using `--hf_token` , `--flock_api_key`, and etc.
- Update the README

**Comment by woobe** [comment]
Here is a screenshot of the CUDA error:

![2024_06_16_validator_cuda_error](https://github.com/FLock-io/llm-loss-validator/assets/2130275/c1e18d19-e0fc-40a3-9617-7539f7e62bc9)
