### ISSUE TITLE
validation bash script - start.sh fail to run on multiple tasks 

### ISSUE THREAD

**Issue by yifanxie** [FLock-io/llm-loss-validator#42]
running multiple task via the start.sh command fails 

```
CUDA_VISIBLE_DEVICES=0 TIME_SLEEP=180 \
bash start.sh \
--hf_token "XXXXXXXXX" \
--flock_api_key "YYYYYYYY" \
--task_id "8,9" \

--validation_args_file validation_config.json.example \
--auto_clean_cache False \
--lora_only False
```

the above generated error message `Error: Got unexpected extra argument (9)`

but calling directly via the validation script works

```
CUDA_VISIBLE_DEVICES=0  FLOCK_API_KEY="XXXXXXXXXXXX" \
HF_TOKEN="YYYYYYYYYY" \
TIME_SLEEP=180 python validate.py loop \
--task_id "8, 9" \
--validation_args_file validation_config.json.example \
--auto_clean_cache False \
--lora_only False
```

**Comment by yifanxie** [comment]
to update, this works, need to pass task ID as env instead of parameters 

`CUDA_VISIBLE_DEVICES=0 TIME_SLEEP=180 TASK_ID=8,9 \
bash start.sh \
--hf_token "XXXXXXXXX" \
--flock_api_key "YYYYYYYY" \
--validation_args_file validation_config.json.example \
--auto_clean_cache False \
--lora_only False`

**Comment by vatsalkshah** [comment]
Update:

You can use the bash script `start.sh` as

```CUDA_VISIBLE_DEVICES=0 TIME_SLEEP=180 \
bash start.sh \
--hf_token "XXXXXXXXX" \
--flock_api_key "YYYYYYYY" \
--task_id 8,9 \
--validation_args_file validation_config.json.example \
--auto_clean_cache False \
--lora_only False

```

without space between 8, and 9.
